### ISSUE TITLE
Training mnist_saved_model returns "[Errno 101] Network is unreachable"

### ISSUE THREAD

**Issue by aahusarenko** [saphanaacademy/EML#3]
Hello,

While training mnist_saved_model.py, I get an error, "IOError: [Errno socket error] [Errno 101] Network is unreachable". I have had proxy issues in the past that has giving me similar issues, but so far I am unable to find a solution for this case. Can anyone shed a light on what might be the issue?

Thanks and Best,
Alex Husarenko

**Comment by saphanaacademy** [comment]
Hi Alex,
Can you check that your TensorFlow machine has a public ip address?
Thanks,
Philip

**Comment by aahusarenko** [comment]
Hi Philip,

Thanks for the quick reply! I just tried to check the public IP address with "dig +short myip.opendns.com @resolver1.opendns.com", "dig TXT +short o-o.myaddr.l.google.com @ns1.google.com", and "host myip.opendns.com resolver1.opendns.com", but all three returned "connection timed out; no servers could be reached".

Would this cause the issue I'm having with training?

Best,
Alex

**Comment by aahusarenko** [comment]
I found out what the issue was! The SOURCE_URL variable in the mnist_input_data.py file was set to 'https://storage.googleapis.com/cvdf-datasets/mnist/'. When I enter this url in my browser I get an access denied error. However, when I changed the variable to point to Yann's Website, 'http://yann.lecun.com/exdb/mnist/', it works perfectly!
